from game.map.map import MAP_1

MAP_HEIGHT_TILES: int = len(MAP_1)
MAP_WIDTH_TILES = len(MAP_1[0])
TEXTURE_SIZE: int = 128
TILE_PIXEL_SIZE: int = 32
GLOBAL_SCALING: float = TILE_PIXEL_SIZE / TEXTURE_SIZE
SCREEN_WIDTH = MAP_WIDTH_TILES * TILE_PIXEL_SIZE
SCREEN_HEIGHT = MAP_HEIGHT_TILES * TILE_PIXEL_SIZE
SCREEN_TITLE: str = "MINI DUNGEON"
